### ISSUE TITLE
Ingest and flatten information we want from OGMS Ontology

### ISSUE THREAD

**Issue by lauralorenz** [ayota/ddl_nlp#1]
Placeholder right now for discussion about the OGMS Ontology.

input: ontology URLs that are in rdf/xml
output: sentences
- [ ] add in more instance level OWLs
- [x] parameterize data directory location

**Comment by lauralorenz** [comment]
This ontology describes the meta relationships from two papers: [Toward and Ontological Treatment](http://ontology.buffalo.edu/medo/Disease_and_Diagnosis.pdf) and [On Carcinoma and other pathological entities](http://ontology.buffalo.edu/bio/ISMB/ISMB_Bio-ontologies.pdf).

A graphical interface to this ontology is available at [OntoBEE](http://www.ontobee.org/ontology/OGMS).

The ontology is available as an XML/RDF document parseable by `rdflib`, a pure Python package that wraps an in-memory SPARQL service (along with support for other backends) allowing you to parse and query directly from RDF sources.

The RDF file is very concise, using URIRefs instead of Literals to present the majority of the relationships. Some example relationships are:

> (rdflib.term.URIRef(u'http://purl.obolibrary.org/obo/OGMS_0000063'), rdflib.term.URIRef(u'http://purl.obolibrary.org/obo/IAO_0000119'), rdflib.term.Literal(u'http://ontology.buffalo.edu/medo/Disease_and_Diagnosis.pdf'))
> [disease course](http://www.ontobee.org/ontology/OGMS?iri=http://purl.obolibrary.org/obo/OGMS_0000063) -> [definition source](http://purl.obolibrary.org/obo/IAO_0000119) -> rdflib.term.Literal(u'http://ontology.buffalo.edu/medo/Disease_and_Diagnosis.pdf')
> 
> (rdflib.term.URIRef(u'http://purl.obolibrary.org/obo/OGMS_0000037'), rdflib.term.URIRef(u'http://purl.obolibrary.org/obo/IAO_0000115'), rdflib.term.Literal(u'Homeostasis that is clinically abnormal for an organism of a given type and age in a given environment.', lang=u'en'))
> [abnormal homeostasis](abnormal homeostasis) -> [definition](http://purl.obolibrary.org/obo/IAO_0000115) -> rdflib.term.Literal(u'Homeostasis that is clinically abnormal for an organism of a given type and age in a given environment.', lang=u'en')

If we want to use this, we need to be able to resolve the URIs into Literals so we can write them into JSON or whatever. I tried a pass with SPARQL though I can't get my  head around the query language to be able to interact with the graph from OGMS. 

Some of the URIRefs come from other ontologies (e.g. the Basic Formal Ontology, an example of which is the use of the class [generically dependent continuant](http://www.ontobee.org/ontology/BFO?iri=http://purl.obolibrary.org/obo/BFO_0000031)) so this RDF is not entirely self containing which I think is making the parsing a little more difficult. In that case we will need to load the dependant graph as well and find a way to replace URIRefs with their resolved literals either from within the graph or from an external resource such as OntoBEE.

**Comment by dvetal** [comment]
So I found a basis way to get the URIs and literals out of the parsed rdflib.Graph().
 it is  .toPython() on any rdf.term.literal OR rdf.termURIRef.

**Comment by lauralorenz** [comment]
Closed by #20
