### ISSUE TITLE
Ingest medical textbooks

### ISSUE THREAD

**Issue by lauralorenz** [ayota/ddl_nlp#10]
We do not have direct access to a large enough corpus of data so we may have to build it ourselves. We want to mash up wikipedia, medical textbooks, and medical abstracts that are sure to cover our evaluation metric dataset. This issue is specifically intended to address ingesting medical textbooks. Possible places to find medical textbooks might be:
- [archive.org](https://archive.org/) - lots of textbooks, mostly in image form though
- [Smithsonian's transcription center](https://transcription.si.edu/) ? who knows if this is useful
- somewhere online 

Honestly we feel like we only need one so some hard core google fu for one or two in text form that we can programmatically retrieve (or simply one time click and download) would be sufficient.

Input: none
Output: medical textbook(s) as a flat text file on disk

**Comment by ayota** [comment]
this was incorporated into the ingestion module.
