### ISSUE TITLE
Drake: Get drake to run the full training process

### ISSUE THREAD

**Issue by dvetal** [ayota/ddl_nlp#16]
We need to get the Drakefile we have to run the full ingestion, fold_generation, and training on each fold in one single run.

**Comment by dvetal** [comment]
#17 Closes this issue once @ayota merges it in

**Comment by dvetal** [comment]
The scope for running the drake file BEGINS: When all of the corpuses have been placed in our folder structure where required.  the drake file process ENDS with post evaluation being complete.

**Comment by lauralorenz** [comment]
1. Remove ingestion piece from drakefile
2. Update all steps until the evaluation step
3. Once @ayota finishes QAing #32 we will get that part in too
