### ISSUE TITLE
Clean up the text

### ISSUE THREAD

**Issue by ayota** [ayota/ddl_nlp#21]
The text pulled in as abstracts and wikipedia has a bunch of weird shit in it. Altering generate_folds.py to include rules to clean this up a bit so the sentences generated are as complete and sentence-y as possible.

We are going to:
- remove all html tags {<-->)
- remove all latex ({--} and ${--})
- remove headers from wikipedia articles
- remove new lines and carriage returns (this messes up the tokenize script)
- remove all non-ascii characters (like copyright symbols)
- remove extraneous spaces (this also messes up the tokenize script)
- remove sentences less than 7 words long, that don't end with a period, don't start with a capital letter, or start with a number.

**Comment by lauralorenz** [comment]
Being worked on on branch [iss21_cleantext](https://github.com/ayota/ddl_nlp/tree/iss21_cleantext) (PR TBA)

**Comment by lauralorenz** [comment]
Closed by #31.
