### ISSUE TITLE
Update README to represent proper directory structure during different steps

### ISSUE THREAD

**Issue by lauralorenz** [ayota/ddl_nlp#25]
README is out of date about what shape the file system should look like during the process. We're using the README as specs for our glue together scripts so this issue is to clean it up.

Change the example directories listed for the generate folds script in the README to be based off runs, not single terms (e.g. "jazz") since we got away from single terms and do it by multiple terms at a time.

**Comment by dvetal** [comment]
PR #20 resolved this.
