### ISSUE TITLE
Grabbing Relevant Terms

### ISSUE THREAD

**Issue by dvetal** [ayota/ddl_nlp#35]
Right now we have a process which starts with grabbing terms from a text file to run the get_corpus.py process.  However, there are only certain terms that we are really interested in.  Those 'terms of extreme interest' can be generated from fun_3000.evaluation.similarity_evaluation.UMLS.get_words_list function.  We basically want this function to run and have some capability that saves this to a file.  Ultimately, we probably just want this to run within drake as the activity that kicks off the whole process.  Another option is to just run that function one time and save the result to the location where we want the file for terms to exist and add it to configuration control. Your call.

**Comment by lauralorenz** [comment]
Dupe/redesigned in #39
