### ISSUE TITLE
Update word2vec.py to fit into revised workflow

### ISSUE THREAD

**Issue by ayota** [ayota/ddl_nlp#36]
Word2vec.py script needs a bit of attention to confirm it's still doing what we want. This is the start of a list of things we need to look at.
- [x] Right now the readme and what the function actually does are out of sync. Fix readme/confirm word2vec.py actually generates a model specific to each fold
- [ ] Edit automagically generated filename to include data dir name (in our case, {SOME RUN}), **as well as** the fold number (e.g., {SOME RUN}_{SOME FOLD}.model) to reduce confusion.
- [ ] Other things TK

**Comment by lauralorenz** [comment]
Irrelevant now given the new directory structure and taking out the multiple foldsiness. Closing
