### ISSUE TITLE
Make readme for evaluation script

### ISSUE THREAD

**Issue by ayota** [ayota/ddl_nlp#37]
Add section to main readme that gives high level overview of what the evaluation script does and how to use it.

We think the current docs are missing
- [ ] what the score actually is (math)
- [ ] example output
- [ ] manual example does not include evaluation example, add that and move all the wikipedia manual example part into the github wiki

**Comment by lauralorenz** [comment]
Getting rid of this one since its intent is so out of date. However we will need README updates when we do settle on a new evaluation tactic, but that should be shipped with the evaluation code or if it is not open a new issue specific to its needs. Closing
