### ISSUE TITLE
Retrieve term list directory from a function

### ISSUE THREAD

**Issue by dvetal** [ayota/ddl_nlp#39]
Right now out get_corpus.py file expects the user to provide a file that includes the terms we want to search for.  However, we have built a function similarity_evalution.FEATURE_BUILDER.get_words_list that returns the unique term list from the UMNSRS_similarity.csv file.  We should add an option to simply grab the terms from this location.

**Comment by dvetal** [comment]
For now this is a low priority.  We have a file that has all of the search terms called eval_words in the data directory.

**Comment by lauralorenz** [comment]
Closing this. We think that the input terms needs to be a larger set than just what is in the evaluation set, and should be separately curated in any case.
