### ISSUE TITLE
Ingest specific wikipedia articles

### ISSUE THREAD

**Issue by lauralorenz** [ayota/ddl_nlp#8]
We do not have direct access to a large enough corpus of data so we may have to build it ourselves. We want to mash up wikipedia, medical textbooks, and medical abstracts that are sure to cover our evaluation metric dataset. This issue is specifically intended to address ingesting specific wikipedia articles that
- include entries for all terms from the evaluation metric dataset
- use a radius parameter to include a radius of similar entries from the base entry

Probably should simply build off of our existing [`wikipedia_ingestion.py`](https://github.com/ayota/ddl_nlp/blob/078bc7c0a778c142a754ee2caea75c02441ab97d/fun_3000/ingestion/wikipedia_ingest.py) but [throw the `results` parameter from the `wikipedia` package in there](https://wikipedia.readthedocs.org/en/latest/code.html#wikipedia.search).

Input: evaluation metric dataset in csv
Output: all the related wikipedia articles as a flat text file to disk

**Comment by dvetal** [comment]
This was merged.
