### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by ayota** [ayota/ddl_nlp#9]
**Identifying synonyms** 
Using the [UMLS data set](http://rxinformatics.umn.edu/SemanticRelatednessResources.html), we use the 566 synonyms to do two related tasks:
- Logistic scale: Take top quartile (~140 words) as "very similar" (=1) and mark all others as "not similar" (0). Get word2vec vectors for train/test pairs, find cosine distance between vectors and build a classifier off that.
- Multivariate scale: Use coder's continuous scale (maybe just take mean and ignore standard deviation?) to train multivariate regression model to predict score of test set of pairs.

**Comment by lauralorenz** [comment]
Identifying synonyms using multivariate scale is in the branch https://github.com/ayota/ddl_nlp/tree/post_gensim_similarity_ml (PR https://github.com/ayota/ddl_nlp/pull/32)
